# Generated by Django 3.0.8 on 2020-07-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_num_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.CharField(default=None, max_length=1024),
            preserve_default=False,
        ),
    ]
